# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: INT
    values:
    - INT
    - PROD
  - name: projectName
    displayName: ProjectName
    type: string
    default: tbv
  - name: variableGroup
    type: string
    values:
      - IntGroup
      - ProdGroup
  - name: branch
    type: string
    values:
      - int-branch
      - prod-branch


trigger:
variables:
  - name: ${{parameter.branch}}
    


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  variables:
  - group: ${{parameters.variableGroup}}

  - ${{if eq(variables['Build.SourceBranchName'], 'int')}}:
      ${{parameters.variableGroup}}: IntGroup
      ${{parameters.environment}}: INT

  - ${{if eq(variables['Build.SourceBranchName'], 'master')}}:
      ${{parameters.variableGroup}}: ProdGroup
      ${{parameters.environment}}: PROD
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(parameters.environment)
    pool: 
     vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: app90888'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(variable.webappName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
